[package]
name = "svg-revolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["svg"] }
smol_str = "0.2"
winit = "0.29.0"
